# Generated by Django 4.2.4 on 2023-09-02 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('build_quality', models.PositiveSmallIntegerField(choices=[(0, 'عالی'), (1, 'خوب'), (2, 'استاندارد')], default=0)),
                ('city', models.PositiveSmallIntegerField(choices=[], default=0)),
                ('area', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=0)),
                ('length', models.PositiveSmallIntegerField(default=0)),
                ('floor', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(1)])),
                ('underground_floor', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('lobby', models.BooleanField(choices=[(True, 'دارد'), (False, 'ندارد')], default=0)),
                ('type_of_structure', models.PositiveSmallIntegerField(choices=[(0, 'بتنی'), (1, 'فولادی')], default=0)),
                ('roof_type', models.PositiveSmallIntegerField(verbose_name=((0, 'تیرچه بتنی'), (1, 'تیرچه فولادی')))),
            ],
        ),
    ]
