# Generated by Django 4.2.4 on 2023-09-03 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_projectfields_city_alter_projectfields_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfields',
            name='floor',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='projectfields',
            name='lobby',
            field=models.BooleanField(choices=[(True, 'دارد'), (False, 'ندارد')], default=True),
        ),
        migrations.AlterField(
            model_name='projectfields',
            name='underground_floor',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
