# Generated by Django 4.2.4 on 2023-09-03 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_projectfields_floor_alter_projectfields_lobby_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectFields',
            new_name='ProjectInputs',
        ),
    ]
