# Generated by Django 4.2.4 on 2008-06-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_projectfields_projectinputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinputs',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
