# Generated by Django 4.2.4 on 2023-09-07 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_projectinputs_build_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinputs',
            name='area',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='projectinputs',
            name='build_quality',
            field=models.PositiveSmallIntegerField(choices=[(0, 'استاندارد'), (1, 'خوب'), (2, 'عالی')]),
        ),
        migrations.AlterField(
            model_name='projectinputs',
            name='city',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='projectinputs',
            name='floor',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='projectinputs',
            name='length',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='projectinputs',
            name='lobby',
            field=models.BooleanField(choices=[(True, 'دارد'), (False, 'ندارد')]),
        ),
        migrations.AlterField(
            model_name='projectinputs',
            name='roof_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'تیرچه بتنی'), (1, 'تیرچه فولادی')]),
        ),
        migrations.AlterField(
            model_name='projectinputs',
            name='type_of_structure',
            field=models.PositiveSmallIntegerField(choices=[(0, 'بتنی'), (1, 'فولادی')]),
        ),
        migrations.AlterField(
            model_name='projectinputs',
            name='underground_floor',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='projectinputs',
            name='width',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
