"""
Django settings for HomeCalculator project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-me5h5i-7*strz3v3po)7%$eixl=tb1s9!_jcsmgj#!x+iq(*se'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'users',
    'price',
    'rest_framework',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HomeCalculator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HomeCalculator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
    'SLIDING_TOKEN_LIFETIME': timedelta(days=7),
    'SLIDING_TOKEN_REFRESH_ON_LOGIN': True,
    'SLIDING_TOKEN_REFRESH_ON_REFRESH': False,
    'SLIDING_TOKEN_REFRESH_AFTER_INACTIVITY': timedelta(hours=1),
    'SLIDING_TOKEN_REFRESH_ON_PASSWORD_CHANGE': True,  
    'SLIDING_TOKEN_REFRESH_ON_ACTIVE': False,
    'SLIDING_TOKEN_REFRESH_ON_INACTIVE': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': '-----BEGIN PRIVATE KEY-----MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDirmBurrXtwUHuw2gP35IsB5rgMTIoaUHREU+6Y9f+r9kBJsu4/zIRqUcHD8v8trqyi0W2uQGX13yWIJVolv0msPv57xXM2LfBPQO4RJ8QWrhomhoRXt3lqlAZQAgByM/kyL6Nn3e2DdY57mklD6tEHgplqU3wxCeKC0md57vBZ6xYXEvG9t+iG3akH0+RRsYsEAMBfaWxZItSG9sM0U9lzgdWobC2HoLxtXrgkPCalBjj458XDJ3o7RGc17kGqqX5BdAoRnbmd79zDA+NQFxCRdj8JU6wJrT0sFWYNO9YM4FCnv1VP1MwSCpDDcFVEJZXnJQDWLp6ZCNfGtBJO49BAgMBAAECggEAKYQsbzkaYvApRjSNw5J78Ap4iCUafaJBhqv4ATg2IBRO11Imr7w1jFyHgLiY8LD64qZ1XzDlJM03qTtQgfZdaQ+zJqRuRrVOelrVapNO2qzy512J9rJ8S4r03psGnGUOBmXp2IBjaXmBSdzrbvk+sdwapWHrv3P9ld/ZXM1LavFcnq5m34bPyut9i00ozl1RZM/bzvzZsn2rsxUyg+ycD55haTGEjA0XiF1pDSjpc2MTAOd/ZX5dUEwWbG3iPW3M+H7ypnGht+7dkGU2K7YC8IwqvKldYCAc3IytoaI6sanBi+lCCFszGmzHUB0VOBjx5rJhPPJ8vmGNQR0vwXVo/QKBgQD8SNHKnGsulRTCJOD7zSDqfBUQoGuMMbvC6p/MjmN8udc6063v0idj+rUe6pmpigSOelqvQtnpHEnLFazJC+/gL2pjNrl0YkQfKqj2Kf522Q6O6YNkmGCDIeDwvxfAt7NtYAacDPr8BPMGnJaSiMBsbz6fnpQWxffV+ajcbZhWIwKBgQDmBQafJ6bbTrBm7nmuRWSWxh0EBU231JnT7TafB/h6AaEUvLsyeKaIBE+wxSWcPgrJb9vPn7GRvkv8ZvS1FgzFLxvcE06Zwzak4lDqZ16s0N4nT9ICHntrPuOQ/YuRokLMQGDtq+KVoCt9w2uomTUvDizxvfJEQ8iYq3+KkbYRSwKBgFoKK0XiuaYwcu4vd1SnC15k1qfOeVPZ1Cdm0Y2SLBOxyA0oy2VSXdii+82C8UC/D41CQedXNqqp+/RNUhOW/Q/IHHI4b8wH3kQ5V4Az0KveIAIFeW2HrLpgdwW1TebsKU+Z/AHp6BHWOl5buKmnwPVyZqlVUYknMqLdrdSuELZ9AoGAWH7Kg2T//xQRLijFy9SK1K837poTwowa+rwi7aBlaptB2/aYltxwRZhTCJFw3OHJyKIukXzBFm9+UIdT0m+/TgXH1C3haar/VQR1WRmYBSj+r2U4SPRtS1+QsfG6RreEt4x1PjuJG0PaN7J9swnuukHb7M3FbZoejQ4+LZPN1m0CgYA/XDAxJxJ4fYx8jgD6V2J0t+ZVw/4HAQ9VbcGPT5K7SEou5Qm/0YnjFuMKxSlx6zI+3GuMlCRhIKy/6Pw20wE9vU9plRCMvlrEBnDStwJ5ZwWuAYUVLbsBDNkueFCaHurEDrFFi0bQlCE2qzr2Hv7La1KpLsEDXgqVWEjKKvtXzQ==-----END PRIVATE KEY-----',
    'VERIFYING_KEY': '-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4q5gbq617cFB7sNoD9+SLAea4DEyKGlB0RFPumPX/q/ZASbLuP8yEalHBw/L/La6sotFtrkBl9d8liCVaJb9JrD7+e8VzNi3wT0DuESfEFq4aJoaEV7d5apQGUAIAcjP5Mi+jZ93tg3WOe5pJQ+rRB4KZalN8MQnigtJnee7wWesWFxLxvbfoht2pB9PkUbGLBADAX2lsWSLUhvbDNFPZc4HVqGwth6C8bV64JDwmpQY4+OfFwyd6O0RnNe5Bqql+QXQKEZ25ne/cwwPjUBcQkXY/CVOsCa09LBVmDTvWDOBQp79VT9TMEgqQw3BVRCWV5yUA1i6emQjXxrQSTuPQQIDAQAB-----END PUBLIC KEY-----',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'username',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'UPDATE_LAST_LOGIN': True,
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'